#!/usr/bin/env python3

import os
import sys

import onewire
import paho.mqtt.publish


if "OW2MQTT_DEVICE" in os.environ:
    device = os.environ["OW2MQTT_DEVICE"]
else:
    device = "/dev/ttyUSB0"

if "OW2MQTT_BROKER" in os.environ:
    broker = os.environ["OW2MQTT_BROKER"]
else:
    broker = "localhost"

try:
    ow = onewire.Onewire(device)
    messages = []
    for sensor in ow.find():
        for attr in ["temperature", "humidity"]:
            topic = f"1wire/{sensor.family}.{sensor.id}/{attr}"
            try:
                payload = sensor.read_float(attr)
            except AttributeError as error:
                if "OW2MQTT_DEBUG" in os.environ:
                    print(error)
                continue
            if "OW2MQTT_DEBUG" in os.environ:
                print(f"{topic} {payload}")
            messages.append({"topic": topic, "payload": payload})
    paho.mqtt.publish.multiple(messages, hostname=broker)
except Exception as error:
    print(error)
    sys.exit(1)
